# Generated by Django 5.0 on 2024-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
