# Generated by Django 5.0 on 2024-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brq_model_validated_by_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brq_model',
            name='desc_dmg_personne',
            field=models.TextField(blank=True, default='/'),
        ),
    ]
