# Generated by Django 5.0 on 2024-05-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_brq_model_desc_dmg_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brq_model',
            name='cause_ai',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='clas_ai',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='date_ai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_degats_corporels',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_degats_environnementaux',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_degats_materiels',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_deroulement',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_dmg_biens',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_dmg_env',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_lieu',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='desc_succincte',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='dispositons_prise',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='fatal_entre_prise',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='fatal_etrangers',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='fatal_prestataire',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='fatal_tiers',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='lieu_ai',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='nature_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.natureai'),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='nbr_blesse',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='brq_model',
            name='temp_ai',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
