# Generated by Django 5.0 on 2024-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_brq_model_cause_ai_alter_brq_model_clas_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brq_model',
            name='clas_ai',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
