# Generated by Django 5.0 on 2024-05-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_brq_model_clas_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='brq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brq_model'),
        ),
    ]
